version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./rag-pdf-chatbot-backend:/app
    env_file:
      - .env  # ✅ Load API keys from .env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000  # ✅ Docker networking for backend
